/*
  Auto-generated by `prisma migrate dev` during Phase 1 setup.

  Purpose: close a pre-existing feature-006 drift left by migration
  `20260224155034_admin_panel_redesign_models` where `users.role_id` was
  modeled as required but left nullable in the database. This migration is
  NOT a Phase 1 schema change; it fixes the drift so Phase 1 validation
  (`prisma migrate dev`) reports the database as in sync.

  Warnings:

  - Made the column `role_id` on table `users` required. This step will fail if there are existing NULL values in that column.

*/
-- AlterTable
ALTER TABLE "users" ALTER COLUMN "role_id" SET NOT NULL;
