codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 70%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/test/**"
  - "**/*.d.ts"
  - "**/vite.config.ts"
  - "**/vitest.config.ts"
  - "**/.eslintrc.*"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/node_modules/**"
  - "**/*.config.js"
  - "**/*.config.ts"
