/**
 * Configurator Internal Email Template
 * =============================================================================
 *
 * PURPOSE:
 * Generates the HTML and plain-text email content sent to the internal
 * Modular House team whenever a customer submits a configurator quote
 * request. The email contains every detail the sales team needs to
 * follow up: customer contact information, the configured product
 * specification (finishes, add-ons, total price), and the generated
 * quote reference number.
 *
 * DESIGN DECISIONS:
 * - All CSS is inlined to maximise compatibility across email clients
 *   (Gmail, Outlook, Apple Mail) which strip <style> blocks.
 * - The data contract is defined via a dedicated interface rather than
 *   re-using the Prisma model, keeping the template decoupled from the
 *   persistence layer (Open-Closed Principle).
 * - A plain-text fallback is always generated alongside HTML so that
 *   clients with HTML disabled still receive a readable notification.
 * - Price formatting uses the EUR locale (en-IE) to match the Irish
 *   market the business operates in.
 *
 * =============================================================================
 */


/* =============================================================================
   SECTION 1: DATA CONTRACT
   -----------------------------------------------------------------------------
   Defines the shape of data required to render the internal notification
   email. Each field maps to a value collected during the configurator
   submission flow or generated by the backend (e.g. quoteNumber).
   ============================================================================= */

/** Represents a single selected add-on for display in the email. */
export interface ConfiguratorAddonItem {
  /** Human-readable add-on name (e.g. "Underfloor Heating"). */
  readonly name: string;
  /** Price of the add-on in euro cents. */
  readonly priceCents: number;
}

/**
 * Complete data payload required to build the internal configurator
 * notification email. All string fields are expected to be pre-sanitised
 * before being passed to the template builder.
 */
export interface ConfiguratorInternalEmailData {
  /** Generated quote reference (e.g. "Q2610005"). */
  readonly quoteNumber: string;
  /** ISO-8601 date string of the submission timestamp. */
  readonly submittedAt: string;

  /* -- Customer contact details ------------------------------------------- */
  readonly firstName: string;
  readonly email: string;
  readonly phone: string;
  readonly eircode: string;

  /* -- Product configuration ---------------------------------------------- */
  /** Display name of the configured product (e.g. "The Studio"). */
  readonly productName: string;
  /** Product dimensions as a formatted string (e.g. "5m x 5m"). */
  readonly productDimensions: string;
  /** Product floor area in square metres (e.g. "25"). */
  readonly productArea: string;
  /** Name of the selected exterior cladding finish. */
  readonly exteriorFinish: string;
  /** Name of the selected interior wall finish. */
  readonly interiorFinish: string;
  /** List of selected add-ons with individual prices. */
  readonly addons: ReadonlyArray<ConfiguratorAddonItem>;
  /** Total configured price in euro cents (base + add-ons). */
  readonly totalCents: number;

  /* -- Scheduling --------------------------------------------------------- */
  /** Customer's preferred date: "asap" or an ISO date string. */
  readonly preferredDate: string;
  /** Optional free-text message from the customer. */
  readonly message: string;
}

/** Return type for all template builder functions. */
export interface EmailTemplateResult {
  readonly subject: string;
  readonly html: string;
  readonly text: string;
}


/* =============================================================================
   SECTION 2: UTILITY HELPERS
   -----------------------------------------------------------------------------
   Small pure functions used during template rendering. Extracted here to
   keep the main builder function focused on structure and layout.
   ============================================================================= */

/**
 * Formats a value in euro cents as a human-readable EUR string.
 * Uses the Irish English locale to match the target market.
 *
 * @param cents - Price in euro cents (e.g. 150000 for EUR 1,500.00).
 * @returns Formatted currency string (e.g. "EUR 1,500.00").
 */
function formatEurCents(cents: number): string {
  return new Intl.NumberFormat('en-IE', {
    style: 'currency',
    currency: 'EUR',
  }).format(cents / 100);
}

/**
 * Converts the preferred date value into a human-readable label.
 * If the value is "asap", returns a descriptive phrase. Otherwise
 * attempts to parse the value as a date and format it.
 *
 * @param value - Either "asap" or an ISO date string.
 * @returns A display-friendly date string.
 */
function formatPreferredDate(value: string): string {
  if (value.toLowerCase() === 'asap') {
    return 'As Soon As Possible';
  }
  const parsed = new Date(value);
  if (isNaN(parsed.getTime())) {
    return value;
  }
  return parsed.toLocaleDateString('en-IE', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

/**
 * Escapes special HTML characters to prevent rendering issues in
 * email clients. Handles the five characters that are significant
 * in HTML markup.
 *
 * @param text - Raw string that may contain HTML-special characters.
 * @returns Escaped string safe for insertion into HTML content.
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}


/* =============================================================================
   SECTION 3: TEMPLATE BUILDER
   -----------------------------------------------------------------------------
   The main exported function that assembles the complete email content.
   The HTML layout uses a single-column table-based structure for maximum
   email client compatibility. Outlook in particular requires table-based
   layouts as it uses the Word rendering engine.
   ============================================================================= */

/**
 * Builds the internal notification email for a configurator submission.
 *
 * The generated email provides the sales team with a complete overview
 * of the customer's configuration including product details, finish
 * selections, add-ons with individual prices, and the total estimate.
 *
 * @param data - The complete configurator submission data.
 * @returns An object containing the email subject, HTML body, and
 *          plain-text fallback.
 */
export function buildConfiguratorInternalEmail(
  data: ConfiguratorInternalEmailData
): EmailTemplateResult {
  const {
    quoteNumber,
    submittedAt,
    firstName,
    email,
    phone,
    eircode,
    productName,
    productDimensions,
    productArea,
    exteriorFinish,
    interiorFinish,
    addons,
    totalCents,
    preferredDate,
    message,
  } = data;

  /* -- Subject line ------------------------------------------------------- */
  const subject = `[Modular House] New Configurator Quote ${quoteNumber} from ${firstName}`;

  /* -- Formatted values for display --------------------------------------- */
  const formattedTotal = formatEurCents(totalCents);
  const formattedDate = formatPreferredDate(preferredDate);
  const submissionDate = new Date(submittedAt).toLocaleString('en-IE', {
    dateStyle: 'full',
    timeStyle: 'short',
  });

  /* -- Add-ons HTML rows -------------------------------------------------- */
  const addonsHtmlRows = addons.length > 0
    ? addons
        .map(
          (addon) =>
            `<tr>
              <td style="padding: 6px 12px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #374151; border-bottom: 1px solid #f3f4f6;">${escapeHtml(addon.name)}</td>
              <td style="padding: 6px 12px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #374151; border-bottom: 1px solid #f3f4f6; text-align: right;">${formatEurCents(addon.priceCents)}</td>
            </tr>`
        )
        .join('\n')
    : `<tr><td colspan="2" style="padding: 6px 12px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #9ca3af; border-bottom: 1px solid #f3f4f6;">No add-ons selected</td></tr>`;

  /* -- Add-ons plain-text lines ------------------------------------------- */
  const addonsTextLines = addons.length > 0
    ? addons.map((addon) => `  - ${addon.name}: ${formatEurCents(addon.priceCents)}`).join('\n')
    : '  None';

  /* -- Customer message section (conditional) ----------------------------- */
  const messageHtmlBlock = message
    ? `
      <tr>
        <td style="padding: 20px 24px 0 24px;">
          <h3 style="margin: 0 0 8px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827; text-transform: uppercase; letter-spacing: 0.5px;">Customer Message</h3>
        </td>
      </tr>
      <tr>
        <td style="padding: 8px 24px 20px 24px;">
          <div style="padding: 12px 16px; background-color: #f9fafb; border-left: 3px solid #2c5282; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #374151; line-height: 1.6;">${escapeHtml(message).replace(/\n/g, '<br>')}</div>
        </td>
      </tr>`
    : '';

  const messageTextBlock = message
    ? `\nCUSTOMER MESSAGE\n${'-'.repeat(40)}\n${message}\n`
    : '';

  /* -- HTML body ---------------------------------------------------------- */
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(subject)}</title>
</head>
<body style="margin: 0; padding: 0; background-color: #f3f4f6; -webkit-font-smoothing: antialiased;">

  <!-- Outer wrapper table for centering -->
  <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color: #f3f4f6;">
    <tr>
      <td align="center" style="padding: 32px 16px;">

        <!-- Main content container -->
        <table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width: 600px; width: 100%; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">

          <!-- Header -->
          <tr>
            <td style="background-color: #2c5282; padding: 24px; text-align: center;">
              <h1 style="margin: 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 20px; font-weight: 700; color: #ffffff; letter-spacing: 0.5px;">New Configurator Quote</h1>
              <p style="margin: 8px 0 0 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #bee3f8;">${escapeHtml(quoteNumber)} | ${escapeHtml(submissionDate)}</p>
            </td>
          </tr>

          <!-- Customer Details -->
          <tr>
            <td style="padding: 20px 24px 0 24px;">
              <h3 style="margin: 0 0 12px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827; text-transform: uppercase; letter-spacing: 0.5px;">Customer Details</h3>
            </td>
          </tr>
          <tr>
            <td style="padding: 0 24px 20px 24px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280; width: 120px;">Name</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827; font-weight: 600;">${escapeHtml(firstName)}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Email</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;"><a href="mailto:${escapeHtml(email)}" style="color: #2c5282; text-decoration: none;">${escapeHtml(email)}</a></td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Phone</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;"><a href="tel:${escapeHtml(phone)}" style="color: #2c5282; text-decoration: none;">${escapeHtml(phone)}</a></td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Eircode</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;">${escapeHtml(eircode)}</td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding: 0 24px;">
              <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 0;">
            </td>
          </tr>

          <!-- Product Configuration -->
          <tr>
            <td style="padding: 20px 24px 0 24px;">
              <h3 style="margin: 0 0 12px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827; text-transform: uppercase; letter-spacing: 0.5px;">Product Configuration</h3>
            </td>
          </tr>
          <tr>
            <td style="padding: 0 24px 20px 24px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280; width: 120px;">Product</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827; font-weight: 600;">${escapeHtml(productName)}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Dimensions</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;">${escapeHtml(productDimensions)}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Area</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;">${escapeHtml(productArea)} m&sup2;</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Exterior</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;">${escapeHtml(exteriorFinish)}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #6b7280;">Interior</td>
                  <td style="padding: 6px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #111827;">${escapeHtml(interiorFinish)}</td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding: 0 24px;">
              <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 0;">
            </td>
          </tr>

          <!-- Add-ons -->
          <tr>
            <td style="padding: 20px 24px 0 24px;">
              <h3 style="margin: 0 0 12px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827; text-transform: uppercase; letter-spacing: 0.5px;">Selected Add-ons</h3>
            </td>
          </tr>
          <tr>
            <td style="padding: 0 24px 12px 24px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
                ${addonsHtmlRows}
              </table>
            </td>
          </tr>

          <!-- Total Price -->
          <tr>
            <td style="padding: 8px 24px 20px 24px;">
              <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background-color: #f0fdf4; border-radius: 6px;">
                <tr>
                  <td style="padding: 12px 16px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827;">Total Configured Price</td>
                  <td style="padding: 12px 16px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 18px; font-weight: 700; color: #166534; text-align: right;">${formattedTotal}</td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Divider -->
          <tr>
            <td style="padding: 0 24px;">
              <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 0;">
            </td>
          </tr>

          <!-- Preferred Date -->
          <tr>
            <td style="padding: 20px 24px 0 24px;">
              <h3 style="margin: 0 0 8px 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; font-weight: 600; color: #111827; text-transform: uppercase; letter-spacing: 0.5px;">Preferred Date</h3>
            </td>
          </tr>
          <tr>
            <td style="padding: 4px 24px 20px 24px; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 14px; color: #374151;">
              ${escapeHtml(formattedDate)}
            </td>
          </tr>

          <!-- Customer Message (conditional) -->
          ${messageHtmlBlock}

          <!-- Footer -->
          <tr>
            <td style="padding: 16px 24px; background-color: #f9fafb; border-top: 1px solid #e5e7eb;">
              <p style="margin: 0; font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 12px; color: #9ca3af; text-align: center;">This is an automated notification from the Modular House configurator.</p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>
</html>`;

  /* -- Plain-text fallback ------------------------------------------------ */
  const text = `${subject}
${'='.repeat(60)}

QUOTE: ${quoteNumber}
DATE:  ${submissionDate}

CUSTOMER DETAILS
${'-'.repeat(40)}
Name:    ${firstName}
Email:   ${email}
Phone:   ${phone}
Eircode: ${eircode}

PRODUCT CONFIGURATION
${'-'.repeat(40)}
Product:    ${productName}
Dimensions: ${productDimensions}
Area:       ${productArea} m2
Exterior:   ${exteriorFinish}
Interior:   ${interiorFinish}

SELECTED ADD-ONS
${'-'.repeat(40)}
${addonsTextLines}

TOTAL CONFIGURED PRICE: ${formattedTotal}

PREFERRED DATE
${'-'.repeat(40)}
${formattedDate}
${messageTextBlock}
${'='.repeat(60)}
This is an automated notification from the Modular House configurator.`;

  return { subject, html, text };
}
